### PR TITLE
Bump versions of dependencies to address dependency bot findings

### PR DESCRIPTION
**Pull request by strieflin**
Signed-off-by: Sven Trieflinger <sven.trieflinger@de.bosch.com>

### CODE REVIEW

**Comment by strieflin** [comment]
Tests are failing due to change in error message:

`[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.85 s <<< FAILURE! - in io.carbynestack.amphora.service.persistence.datastore.MinioSecretShareDataStoreTest
[ERROR] io.carbynestack.amphora.service.persistence.datastore.MinioSecretShareDataStoreTest.givenNoDataAvailableForGivenId_whenGetSecretShareData_thenThrowAmphoraServiceException  Time elapsed: 0.791 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...-a37b-b0075bb5e779: [null]> but was:<...-a37b-b0075bb5e779: [inputStream]>
	at io.carbynestack.amphora.service.persistence.datastore.MinioSecretShareDataStoreTest.givenNoDataAvailableForGivenId_whenGetSecretShareData_thenThrowAmphoraServiceException(MinioSecretShareDataStoreTest.java:117)`

@sbckr: Can you please have a look. Not sure about the best way to handle this.

**Comment by sbckr** [comment]
@strieflin test was broken due to changes implied with the upgrade on `commons.io`. Please have a look at my latest commits to fix the issue and update 3rd-party license information

**Review by strieflin — COMMENTED** [review]
LGTM

**Review by sbckr — APPROVED** [review]
LGTM

**Pull request merged**
